{
    'Plano Piloto':['Brazlândia', 'Sobradinho', 'Varjão', 'Lago Norte', 'Sudoeste', 'Cruzeiro', 'SIA', 'SCIA_Estrutural', 'Taguatinga'],
    'Gama':['Santa Maria', 'Recanto das Emas', 'Riacho_Fundo_II', 'Park Way'],
    'Taguatinga':['Ceilândia', 'Brazlândia', 'Plano Piloto', 'Vicente Pires', 'SCIA_Estrutural', 'Guará', 'Águas Claras', 'Riacho Fundo', 'Samambaia'],
    'Brazlândia':['Ceilândia','Plano Piloto', 'Sobradinho', 'Sobradinho II'],
    'Sobradinho':['Brazlândia', 'Plano Piloto', 'Planaltina', 'Lago Norte', 'Itapoã'],
    'Planaltina':['Sobradinho II', 'Sobradinho', 'Itapoã', 'Paranoá'],
    'Paranoá':['Planaltina', 'Itapoã', 'Lago Norte', 'Jardim Botânico', 'São Sebastião'],
    'Núcleo Bandeirante':['Águas Claras', 'Guará', 'Candangolândia', 'Lago Sul', 'Park Way', 'Riacho Fundo'],
    'Ceilândia':['Taguatinga','Samambaia', 'Brazlândia'],
    'Guará':['Vicente Pires', 'SCIA_Estrutural', 'SIA', 'Candangolândia', 'Núcleo Bandeirante', 'Águas Claras', 'Taguatinga'],
    'Cruzeiro':['SIA', 'Sudoeste', 'Plano Piloto'],
    'Samambaia':['Ceilândia', 'Taguatinga', 'Riacho Fundo', 'Riacho_Fundo_II'],
    'Santa Maria':['São Sebastião', 'Gama', 'Lago Sul', 'Park Way'],
    'São Sebastião':['Paranoá', 'Jardim Botânico', 'Lago Sul', 'Santa Maria'],
    'Recanto das Emas':['Samambaia', 'Gama', 'Riacho_Fundo_II'],
    'Lago Sul':['Santa Maria', 'Park Way','Núcleo Bandeirante', 'Candangolândia', ],
    'Riacho Fundo':['Samambaia', 'Taguatinga', 'Águas Claras', 'Núcleo Bandeirante', 'Park Way'],
    'Lago Norte':['Plano Piloto', 'Varjão', 'Sobradinho', 'Itapoã', 'Paranoá'],
    'Candangolândia':['Guará','Plano Piloto', 'Lago Sul'],
    'Águas Claras':['Taguatinga', 'Guará', 'Núcleo Bandeirante', 'Riacho Fundo'],
    'Riacho_Fundo_II':['Gama', 'Recanto das Emas', 'Samambaia', 'Riacho Fundo', 'Park Way'],
    'Sudoeste':['SIA', 'Plano Piloto', 'Cruzeiro'],
    'Varjão':['Plano Piloto', 'Lago Norte'],
    'Park Way':['Gama', 'Riacho_Fundo_II', 'Riacho Fundo', 'Núcleo Bandeirante', 'Lago Sul', 'Santa Maria', 'Jardim Botânico', 'São Sebastião'],
    'SCIA_Estrutural':['Taguatinga', 'Plano Piloto', 'SIA', 'Guará', 'Vicente Pires'],
    'Sobradinho II':['Fercal', 'Sobradinho', 'Brazlândia', 'Planaltina'],
    'Jardim Botânico':['Lago Sul', 'Paranoá', 'São Sebastião'],
    'Itapoã':['Lago Norte', 'Sobradinho', 'Planaltina', 'Paranoá'],
    'SIA':['SCIA_Estrutural', 'Plano Piloto', 'Cruzeiro', 'Sudoeste', 'Guará'],
    'Vicente Pires':['Taguatinga', 'SCIA_Estrutural', 'Guará'],
    'Fercal':['Sobradinho', 'Sobradinho II'],
}